version: "3.9"

services:
  backend:
    build: .
    container_name: cmwi-backend
    ports:
      - "3210:3000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql-server
    restart: unless-stopped
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Ensure this is a strong password
      MYSQL_DATABASE: cmwi_db
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      # MODIFIED HEALTHCHECK:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      timeout: 20s # Increased timeout slightly, just in case
      retries: 5
      interval: 10s

volumes:
  mysql-data:
